org: laboulejam
app: aws-typescript
service: aws-typescript
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.hello

plugins:
  - serverless-esbuild
